using System;
using Repositories;

namespace Maven.Repositories
{
    public class MavenSearchEntity : MavenBaseSearchEntity
    {
        public bool Snapshot { get; set; }
        public string BuildNumer { get; set; }  //Generated by repocache
    }
}